
class JSONTransformInterface():

	def toJSON(self):
		""" Function to generate a dictionary representation of this instance. Used for serialization.
		
		"""
		raise NotImplementedError("")

	@classmethod
	def fromJSON(cls, inpDict):
		""" Construct a new instance from the JSON (dictionary) representation. Used for de-serialization (e.g. reading objects from a file)
		
		Args:
			inpDict (dict): JSON (dictionary) representation generated by cls.toJSON() 
				 
		Returns
			outObj (cls): Instance of this class
	 
		"""
		raise NotImplementedError("")



